import "./styles/globals.css"
import Providers from "./store/Providers"
import NavBar from "./components/NavBar"
import Footer from "./components/Footer"
import ButtonBar from "./components/ButtonBar"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <nav>
            <NavBar />
          </nav>
          <main>{children}</main>
          <footer>
            <Footer />
            <ButtonBar />
          </footer>
        </Providers>
      </body>
    </html>
  )
}
